-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(p.PRICE * os.SALES_AMOUNT)
FROM PRODUCT p
JOIN OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SUM(p.PRICE * os.SALES_AMOUNT) DESC, p.PRODUCT_CODE ASC